# Generated by Django 4.2.7 on 2023-11-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="activated",
        ),
        migrations.RemoveField(
            model_name="report",
            name="archived",
        ),
        migrations.AddField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
