# Generated by Django 4.2.7 on 2023-12-18 19:20

import autoslug.fields
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True,
                        editable=False,
                        max_length=200,
                        populate_from="name",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("code", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "Compte",
                "verbose_name_plural": "Comptes",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "contrepartie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrepartie_transactions",
                        to="compte.compte",
                    ),
                ),
                (
                    "partie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partie_transactions",
                        to="compte.compte",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="report.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Ocr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ocr_img", models.ImageField(upload_to="images/")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocr_images",
                        to="report.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "ocr_image",
                "verbose_name_plural": "ocr_images",
                "ordering": ["name"],
            },
        ),
    ]
