# Generated by Django 4.2.7 on 2023-11-29 19:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("date", models.DateTimeField(blank=True, null=True)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "contrepartie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contrepartie_transactions",
                        to="compte.compte",
                    ),
                ),
                (
                    "partie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partie_transactions",
                        to="compte.compte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["date"],
            },
        ),
    ]
