# Generated by Django 4.2.7 on 2023-11-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0002_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
