# Generated by Django 4.2.7 on 2023-12-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compte", "0003_alter_transaction_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ocr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("ocr_img", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
